/** @format */

import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const nunito = Nunito({
	subsets: ['latin'],
	weight: ['200', '300', '400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={nunito.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
